In [4]:
# Import libraries

import numpy as np
import matplotlib.pyplot as plot
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import csv

In [5]:
# Load the data and merge the training files into a single training file

df_train = pd.read_csv('train_values.csv')
df_label = pd.read_csv('Train_Labels.csv')

# Concat an output label from "train_labels" to "train_values" file.

temp = pd.concat([df_train, df_label['heart_disease_present']], axis=1)
df_train = temp

# Change from string to number a "thal" variable in training file.
df_train['thal']=df_train['thal'].map({'normal':0,'reversible_defect':1,'fixed_defect':2})

# Change from string to number a "thal" variable in test file.
df_test=pd.read_csv('test_values.csv')
df_test['thal']=df_test['thal'].map({'normal':0,'reversible_defect':1,'fixed_defect':2})
pd.DataFrame(df_test).to_csv('test.csv', index=False)
print(df_test.shape)

# Generate a processed training file
pd.DataFrame(df_train).to_csv('training.csv', index=False)
print(df_train.shape)


(90, 14)
(180, 15)


In [6]:
x = df_train.iloc[:, 1:14]
#print(x)

thal_dummies=(pd.get_dummies(x.values[:,1]))
thal_dummies_temp = pd.DataFrame(thal_dummies)

chest_dummies=(pd.get_dummies(x.values[:,3]))
chest_dummies_temp = pd.DataFrame(chest_dummies)

sex_dummies=(pd.get_dummies(x.values[:,9]))
sex_dummies_temp = pd.DataFrame(sex_dummies)

#angina_dummies=(pd.get_dummies(x.values[:,12]))
#print(sex_dummies)
#angina_dummies_temp = pd.DataFrame(angina_dummies)
#print(vessels_dummies_temp)


#print(df_train)

(180, 21)


In [7]:
z = df_test.iloc[:,1:14]
thal_dummies=(pd.get_dummies(z.values[:,1]))
thal_dummies_temp = pd.DataFrame(thal_dummies)

chest_dummies=(pd.get_dummies(z.values[:,3]))
chest_dummies_temp = pd.DataFrame(chest_dummies)

sex_dummies=(pd.get_dummies(z.values[:,9]))
sex_dummies_temp = pd.DataFrame(sex_dummies)

#angina_dummies=(pd.get_dummies(z.values[:,12]))
#print(sex_dummies)
#angina_dummies_temp = pd.DataFrame(angina_dummies)
#print(vessels_dummies_temp)


#print(df_test)

(90, 20)


In [8]:
#Create a feature Vector "X" and label Vector "y"
X = df_train.iloc[:,1:-1].values
print(X.shape)
print(X)

y = df_train.iloc[:, -1].values
print(y.shape)
print(y)

z = df_test.iloc[:,1:20].values
print(z.shape)
print(z)

(180, 19)
[[  1.   1.   0. ...  45. 170.   0.]
 [  2.   1.   0. ...  54. 158.   0.]
 [  1.   1.   0. ...  77. 162.   1.]
 ...
 [  2.   0.   1. ...  64. 131.   1.]
 [  1.   1.   0. ...  48. 175.   0.]
 [  1.   1.   0. ...  54. 163.   0.]]
(180,)
[0 0 1 1 0 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0
 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 0 0
 1 1 0 1 1 1 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0
 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 1
 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0]
(90, 19)
[[  2.   0.   1. ...  59. 159.   0.]
 [  1.   1.   0. ...  35. 182.   0.]
 [  2.   0.   1. ...  43. 120.   1.]
 ...
 [  1.   1.   0. ...  42. 178.   0.]
 [  2.   1.   0. ...  46. 152.   1.]
 [  1.   1.   0. ...  43. 171.   0.]]


In [9]:
clf = LogisticRegression(penalty='l2', class_weight='balanced',random_state=0, solver='lbfgs', tol=0.00001, C=1.0, fit_intercept=True, max_iter=30000000).fit(X, y)
a=clf.predict_proba(z[:, :])
df_temp = pd.DataFrame(a)
#print(df_temp)
temp = pd.concat([df_test['patient_id'], df_temp[1]], axis=1)
temp.columns = ['patient_id', 'heart_disease_present']
print(temp)

pd.DataFrame(temp).to_csv('LR_OneHot_thal_chest_sex_Raw_1507_1434.csv', index=False)

   patient_id  heart_disease_present
0      olalu7               0.436488
1      z9n6mx               0.088175
2      5k4413               0.951756
3      mrg7q5               0.042399
4      uki4do               0.937284
5      kev1sk               0.023708
6      9n6let               0.126161
7      jxmtyg               0.960606
8      51s2ff               0.232840
9      wi9mcs               0.122554
10     741h4l               0.390870
11     1ef64a               0.548095
12     wa2ix6               0.401657
13     8167zl               0.993693
14     n6nldr               0.119862
15     ph85fp               0.037441
16     jfan5p               0.009941
17     7c4iz1               0.020270
18     ukigml               0.927417
19     flwvnq               0.045218
20     5i4fw2               0.975741
21     du1pqf               0.208250
22     vs68qz               0.214220
23     pfyez0               0.016264
24     azvkw2               0.438829
25     cird1i               0.942530
2